const menuData = [

{
    category:"飯類",
    items:[
        {
            name:"白飯",
            available:true,
            quantity:true
        },
        {
            name:"粥",
            available:true,
            quantity:true
        },
        {
            name:"稀飯",
            available:true,
            quantity:true
        }]
},
{
    category:"麵類",
    items:[
        {
            name:"番茄義大利麵（直麵、有醬）",
            available:true,
            quantity:true,
            options:[
                {
                    name:"雞胸肉",
                    available:true,
                    quantity:true
                },

                {
                    name:"雞腿",
                    available:true,
                    quantity:true
                },

                {
                    name:"香腸",
                    available:true,
                    quantity:true
                },

                {
                    name:"蝦子",
                    available:true,
                    quantity:true
                }

            ]
        },
        {
            name:"番茄刀削麵（寬麵）",
            available:true,
            quantity:true
        }, 
        {
            name:"蔬菜湯麵",
            available:true,
            quantity:true
        }, 
        {
            name:"肉燥乾麵",
            available:true,
            quantity:true
        }
        , 
        {
            name:"蝦子麵",
            available:true,
            quantity:true
        }
        , 
        {
            name:"來一客泡麵",
            available:true,
            quantity:true, 
            options:[
                {
                    name:"整顆的蛋",
                    available:true,
                    quantity:true
                },

                {
                    name:"蛋花",
                    available:true,
                },

                {
                    name:"青菜",
                    available:true,
                },

                {
                    name:"蝦子",
                    available:true,
                    quantity:true
                }

            ]
        }
        , 
        {
            name:"一蘭泡麵",
            available:true,
            quantity:true, 
            options:[
                {
                    name:"整顆的蛋",
                    available:true,
                    quantity:true
                },

                {
                    name:"蛋花",
                    available:true,
                },

                {
                    name:"青菜",
                    available:true,
                },

                {
                    name:"蝦子",
                    available:true,
                    quantity:true
                }
            ]
        }
    ]
}, 
{
    category:"菜類",
    items:[
        {
            name:"高麗菜(炒)",
            available:true,
            quantity:true
        },
        {
            name:"高麗菜(滷)",
            available:true,
            quantity:true
        },
        {
            name:"炒青菜",
            available:true,
            quantity:true
        },
        {
            name:"烤蔬菜",
            available:true,
            quantity:true, 
            options:[
                {
                    name:"櫛瓜",
                    available:true,
                    quantity:true
                },
                {
                    name:"香菇",
                    available:true,
                    quantity:true
                }, 
                {
                    name:"秋葵",
                    available:true,
                    quantity:true
                },
                {
                    name:"茭白筍",
                    available:true,
                    quantity:true
                },
                {
                    name:"蘆筍",
                    available:true,
                    quantity:true
                }
            ]
        },
        {
            name:"竹筍",
            available:true,
            quantity:true
        },
        {
            name:"豆製品",
            available:true,
            quantity:true
        },
        {
            name:"高麗菜(滷)",
            available:true,
            quantity:true
        },
        {
            name:"滷海帶",
            available:true,
            quantity:true
        }]
},
{
    category:"肉類",
    items:[
        {
            name:"雞腿（煎）",
            available:true,
            quantity:true
        },
        {
            name:"雞排（煎）",
            available:true,
            quantity:true
        },
        {
            name:"雞胸肉（煎）",
            available:true,
            quantity:true
        },
        {
            name:"豬排（煎）",
            available:true,
            quantity:true
        },
        {
            name:"豬肉（肉燥）",
            available:true,
            quantity:true
        },
        {
            name:"蝦子（水煮）",
            available:true,
            quantity:true
        },
        {
            name:"蝦子（煎）",
            available:true,
            quantity:true
        },
        {
            name:"烤香腸",
            available:true,
            quantity:true
        }]
},
{
    category:"蛋類",
    items:[
        {
            name:"玉子燒",
            available:true,
            quantity:true
        },
        {
            name:"茶碗蒸",
            available:true,
            quantity:true
        },
        {
            name:"蔥蛋",
            available:true,
            quantity:true
        },
        {
            name:"玉米炒蛋",
            available:true,
            quantity:true
        },
        {
            name:"洋蔥炒蛋",
            available:true,
            quantity:true
        }]
},
{
    category:"湯類",
    items:[
        {
            name:"番茄蛋花湯",
            available:true,
            quantity:true
        }, 
        {
            name:"紫菜蛋花湯",
            available:true,
            quantity:true
        },
        {
            name:"青菜湯",
            available:true,
            quantity:true
        },
        {
            name:"香菇湯",
            available:true,
            quantity:true, 
            
        }, 
        {
            name:"白蘿蔔湯",
            available:true,
            quantity:true, 
            options:[
                {
                    name:"豬肉",
                    available:true,
                },
                {
                    name:"雞肉",
                    available:true,
                }
            ]
        },
        {
            name:"紅蘿蔔湯",
            available:true,
            quantity:true, 
            options:[
                {
                    name:"豬肉",
                    available:true,
                },
                {
                    name:"雞肉",
                    available:true,
                }
            ]
        },
        {
            name:"竹筍湯",
            available:true,
            quantity:true, 
            options:[
                {
                    name:"豬肉",
                    available:true,
                },
                {
                    name:"雞肉",
                    available:true,
                }
            ]
        }, 
        {
            name:"玉米濃湯",
            available:true,
            quantity:true
        },
        {
            name:"馬鈴薯濃湯",
            available:true,
            quantity:true
        },
        {
            name:"餛飩湯",
            available:true,
            quantity:true
        }]
},
{
    category:"宵夜",
    items:[
        {
            name:"湯圓",
            available:true,
            quantity:true
        },
        {
            name:"蛋餅",
            available:true,
            quantity:true
        },
        {
            name:"巧克力麵包",
            available:true,
            quantity:true
        },
        {
            name:"餅乾",
            available:true,
            quantity:true
        },
        {
            name:"水果",
            available:true,
            quantity:true
        },
        {
            name:"洋芋片",
            available:true,
        },
        {
            name:"爆米花",
            available:true,
        },
        {
            name:"飯糰",
            available:true,
            quantity:true
        }]
},
{
    category:"飲料",
    items:[
        {
            name:"咖啡",
            available:true,
            quantity:true
        },
        {
            name:"烏龍茶",
            available:true,
            quantity:true
        },
        {
            name:"綠茶",
            available:true,
            quantity:true
        },
        {
            name:"紅茶",
            available:true,
            quantity:true
        },
        {
            name:"花茶",
            available:true,
            quantity:true
        },
        {
            name:"柚子茶",
            available:true,
            quantity:true
        },
        {
            name:"水果茶",
            available:true,
            quantity:true
        },
        {
            name:"牛奶",
            available:true,
            quantity:true
        },
        {
            name:"豆漿(有糖)",
            available:true,
            quantity:true
        }, 
        {
            name:"豆漿(無糖)",
            available:true,
            quantity:true
        },
        {
            name:"蜂蜜水",
            available:true,
            quantity:true
        }]
},
{
    category:"甜點",
    items:[
        {
            name:"奶酪",
            available:true,
            quantity:true
        },
        {
            name:"布丁",
            available:true,
            quantity:true
        },
        {
            name:"仙草凍",
            available:true,
            quantity:true
        },
        {
            name:"芋圓",
            available:true,
        },
        {
            name:"豆花",
            available:true,
            quantity:true
        },
        {
            name:"優格",
            available:true,
            quantity:true
        },
        {
            name:"湯圓",
            available:true,
            quantity:true
        },
        {
            name:"蛋塔",
            available:true,
            quantity:true
        },
        {
            name:"冰淇淋",
            available:true,
            quantity:true
        },
        {
            name:"冰棒",
            available:true,
            quantity:true
        }]
},
{
    category:"其他餐點",
    items:[
        {
            name:"水餃",
            available:true,
            quantity:true
        },
        {
            name:"煎餃",
            available:true,
            quantity:true
        },
        {
            name:"煎餛飩",
            available:true,
            quantity:true
        },
        {
            name:"竹筍沙拉",
            available:true,
            quantity:true
        },
        {
            name:"米粉(乾)",
            available:true,
            quantity:true
        },
        {
            name:"米粉(湯)",
            available:true,
            quantity:true
        },
        {
            name:"冬粉(乾)",
            available:true,
            quantity:true
        },
        {
            name:"冬粉(湯)",
            available:true,
            quantity:true
        }]
}];